set_property SRC_FILE_INFO {cfile:C:/Users/EEuser/Desktop/ee2000_lab1/ee2000_lab1.srcs/constrs_1/new/ZedBoard.xdc rfile:../../../ee2000_lab1.srcs/constrs_1/new/ZedBoard.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports {led}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {sw}]
